### ISSUE TITLE
Keeps on Loading ...

### ISSUE THREAD

**Issue by singhalyk86** [hooman-pro/yii2-iviewer#1]
If I use it using config method, after clicking the image, a popup come and the loader keeps on loading..

I checked through Inspect element. 1 error
index.php?r=sprofile%2Fview&id=125:417      Uncaught ReferenceError: $ is not defined

If I use it using direct method, the image captures the entire page. But the zoom and rotate functionality works perfectly.

**Comment by hooman-mirghasemi** [comment]
when loading keep it means that you set wrong image path in data-iviewer-src in the element that have iviewer-gallery-item class
